export const szizleFonts = {
    NunitoBlack: 'Nunito-Black',
    NunitoRegular:'Nunito-Regular',
    NunitoSemiBold:'Nunito-SemiBold',
    NunitoSemiBoldItalic:'Nunito-SemiBoldItalic',
    NunitoLightItalic:'Nunito-LightItalic',
    NunitoLight:'Nunito-Light',
    NunitoItalic:'Nunito-Italic',
    NunitoExtraLightItalic:'Nunito-ExtraLightItalic',
    NunitoExtraLight:'Nunito-ExtraLight',
    NunitoExtraBoldItalic:'Nunito-ExtraBoldItalic',
    NunitoExtraBold:'Nunito-ExtraBold',
    NunitoBoldItalic:'Nunito-BoldItalic',
    NunitoBold:'Nunito-Bold',
  };