export const routes = {
  TutorialNavigation: "TutorialNavigation",
  PreferencesScreen: "PreferencesScreen",
  ChangePasswordScreen: "ChangePasswordScreen",
  AnalyticsDashboardScreen: "AnalyticsDashboardScreen",
  TutorialStep1: "TutorialStep1",
  TutorialStep2: "TutorialStep2",
  TutorialStep3: "TutorialStep3",
  CheckList: "CheckList",
  HomeScreen: "HomeScreen",
  NotificationsScreen: "NotificationsScreen",
  DocumentsScreen: "DocumentsScreen",
  SplashScreen: "SplashScreen",
  LoginScreen: "LoginScreen",
  RegisterScreen1: "RegisterScreen1",
  RegisterScreen2: "RegisterScreen2",
  RegisterScreen3: "RegisterScreen3",
  RegisterScreen4: "RegisterScreen4",
  PrivacyWebView: "PrivacyWebView",
  ReactivatePasswordScreen: "ReactivatePasswordScreen",
  AlertWebViewScreen: "AlertWebViewScreen",
  NewPasswordScreen: "NewPasswordScreen",
  AccountUnlockScreen: "AccountUnlockScreen",
  AccountLockedScreen: "AccountLockedScreen",
  ResetPasswordScreen: "ResetPasswordScreen",
  ForgotPasswordScreen: "ForgotPasswordScreen",
  PhoneVerificationScreen: "PhoneVerificationScreen",
  CongratulationScreen: "CongratulationScreen",
  UnlockNewPasswordScreen: "UnlockNewPasswordScreen",
  TourScreen: "TourScreen",
  AuthNavigation: "AuthNavigation",
  RegisterValidationScreen: "RegisterValidationScreen",
  FingerprintLoginScreen: "FingerprintLoginScreen",
  WelcomeScreen: "WelcomeScreen",
  MainFunctionalNavigation: "MainFunctionalNavigation",
  BottomNavigation: "BottomNavigation",
  DrawerNavigation: "DrawerNavigation",
  AddPolicyScreen: "AddPolicyScreen",
  ImagePreview: "ImagePreview",
  MyProfileScreen: "MyProfileScreen",
  ProfilePhoneVerificationScreen: "ProfilePhoneVerificationScreen",
  PrivacySecurityScreen: "PrivacySecurityScreen",
  LegalScreen: "LegalScreen",
  HelpScreen: "HelpScreen",
  FAQScreen: "FAQScreen",
  WriteToUsScreen: "WriteToUsScreen",
  SubscriptionScreen: "SubscriptionScreen",
  PaymentSuccessfulScreen: "PaymentSuccessfulScreen",
  AttachmentScreen: "AttachmentScreen",
  PolicyDetailScreen: "PolicyDetailScreen",
};
export const insuranceLabels = {
  HomeInsurance: "Home Insurance",
  CarInsurance: "Car Insurance",
  BikeInsurance: "Bike Insurance",
  HealthInsurance: "Health Insurance",
  PetInsurance: "Pet Insurance",
  TravelInsurance: "Travel Insurance",
  GadgetInsurance: "Gadget Insurance",
  SmallBusinessInsurance: "Small Business Insurance",
};
