export const actionTypes = {
  FULL_NAME: "FULL_NAME",

  LOGIN_USER_LOADING: "LOGIN_USER_LOADING",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGINED_USER: "LOGINED_USER",
  LOGIN_USER_FAIL: "LOGIN_USER_FAIL",
  LOGOUT: "LOGOUT",
  // phone verification action types
  PHONE_VERIFICATION_LOADING: "PHONE_VERIFICATION_LOADING",
  PHONE_VERIFICATION_SUCCESS: "PHONE_VERIFICATION_SUCCESS",
  PHONE_VERIFICATION_FAIL: "PHONE_VERIFICATION_FAIL",

  // phone verification action types
  PROFILE_PHONE_VERIFICATION_LOADING: "PROFILE_PHONE_VERIFICATION_LOADING",
  PROFILE_PHONE_VERIFICATION_SUCCESS: "PROFILE_PHONE_VERIFICATION_SUCCESS",
  PROFILE_PHONE_VERIFICATION_FAIL: "PROFILE_PHONE_VERIFICATION_FAIL",

  //validate phone code action types
  VALIDATE_PHONE_CODE_LOADING: "VALIDATE_PHONE_CODE_LOADING",
  VALIDATE_PHONE_CODE_SUCCESS: "VALIDATE_PHONE_CODE_SUCCESS",
  VALIDATE_PHONE_CODE_FAIL: "VALIDATE_PHONE_CODE_FAIL",

  //sign up action types
  SIGN_UP_LOADING: "SIGN_UP_LOADING",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAIL: "SIGN_UP_FAIL",

  //verify email action types
  EMAIL_VERIFICATION_LOADING: "EMAIL_VERIFICATION_LOADING",
  EMAIL_VERIFICATION_SUCCESS: "EMAIL_VERIFICATION_SUCCESS",
  EMAIL_VERIFICATION_FAIL: "EMAIL_VERIFICATION_FAIL",

  //create password action types
  CREATE_PASSWORD_LOADING: "CREATE_PASSWORD_LOADING",
  CREATE_PASSWORD_SUCCESS: "CREATE_PASSWORD_SUCCESS",
  CREATE_PASSWORD_FAIL: "CREATE_PASSWORD_FAIL",

  //Verify Referral action types
  VERIFY_REFERRAL_LOADING: "VERIFY_REFERRAL_LOADING",
  VERIFY_REFERRAL_SUCCESS: "VERIFY_REFERRAL_SUCCESS",
  VERIFY_REFERRAL_FAIL: "VERIFY_REFERRAL_FAIL",

  //forgot password action types
  FORGOT_PASSWORD_LOADING: "FORGOT_PASSWORD_LOADING",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAIL: "FORGOT_PASSWORD_FAIL",

  //reset password action types
  RESET_PASSWORD_LOADING: "RESET_PASSWORD_LOADING",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAIL: "RESET_PASSWORD_FAIL",

  //unlock account action types
  UNLOCK_ACCOUNT_LOADING: "UNLOCK_ACCOUNT_LOADING",
  UNLOCK_ACCOUNT_SUCCESS: "UNLOCK_ACCOUNT_SUCCESS",
  UNLOCK_ACCOUNT_FAIL: "UNLOCK_ACCOUNT_FAIL",

  //verify unlock account action types
  VERIFY_UNLOCK_ACCOUNT_LOADING: "VERIFY_UNLOCK_ACCOUNT_LOADING",
  VERIFY_UNLOCK_ACCOUNT_SUCCESS: "VERIFY_UNLOCK_ACCOUNT_SUCCESS",
  VERIFY_UNLOCK_ACCOUNT_FAIL: "VERIFY_UNLOCK_ACCOUNT_FAIL",

  //save password unlock account action types
  SAVE_PASSWORD_UNLOCK_ACCOUNT_LOADING: "SAVE_PASSWORD_UNLOCK_ACCOUNT_LOADING",
  SAVE_PASSWORD_UNLOCK_ACCOUNT_SUCCESS: "SAVE_PASSWORD_UNLOCK_ACCOUNT_SUCCESS",
  SAVE_PASSWORD_UNLOCK_ACCOUNT_FAIL: "SAVE_PASSWORD_UNLOCK_ACCOUNT_FAIL",

  //save password unlock account action types
  NEW_PASSWORD_LOADING: "NEW_PASSWORD_LOADING",
  NEW_PASSWORD_SUCCESS: "NEW_PASSWORD_SUCCESS",
  NEW_PASSWORD_FAIL: "NEW_PASSWORD_FAIL",

  //biometric enable disable action types
  BIOMETRIC_LOADING: "BIOMETRIC_LOADING",
  BIOMETRIC_SUCCESS: "BIOMETRIC_SUCCESS",
  BIOMETRIC_FAIL: "BIOMETRIC_FAIL",

  //preferences update action types
  PREFERENCES_UPDATE_LOADING: "PREFERENCES_UPDATE_LOADING",
  PREFERENCES_UPDATE_SUCCESS: "PREFERENCES_UPDATE_SUCCESS",
  PREFERENCES_UPDATE_FAIL: "PREFERENCES_UPDATE_FAIL",

  //policy types action types
  POLICY_TYPE_LOADING: "POLICY_TYPE_LOADING",
  POLICY_TYPE_SUCCESS: "POLICY_TYPE_SUCCESS",
  POLICY_TYPE_FAIL: "POLICY_TYPE_FAIL",

  //tour pages action types
  TOUR_LOADING: "TOUR_LOADING",
  TOUR_SUCCESS: "TOUR_SUCCESS",
  TOUR_FAIL: "TOUR_FAIL",

  //profile update action types
  UPDATE_PROFILE_LOADING: "UPDATE_PROFILE_LOADING",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAIL: "UPDATE_PROFILE_FAIL",

  //profile update action types
  UPLOAD_DOCUMENT_LOADING: "UPLOAD_DOCUMENT_LOADING",
  UPLOAD_DOCUMENT_SUCCESS: "UPLOAD_DOCUMENT_SUCCESS",
  UPLOAD_DOCUMENT_FAIL: "UPLOAD_DOCUMENT_FAIL",

  //profile action types
  PROFILE_LOADING: "PROFILE_LOADING",
  PROFILE_SUCCESS: "PROFILE_SUCCESS",
  PROFILE_FAIL: "PROFILE_FAIL",

  //profile pic update action types
  UPDATE_PROFILE_PIC_LOADING: "UPDATE_PROFILE_PIC_LOADING",
  UPDATE_PROFILE_PIC_SUCCESS: "UPDATE_PROFILE_PIC_SUCCESS",
  UPDATE_PROFILE_PIC_FAIL: "UPDATE_PROFILE_PIC_FAIL",

  //change password action types
  CHANGE_PASSWORD_LOADING: "CHANGE_PASSWORD_LOADING",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAIL: "CHANGE_PASSWORD_FAIL",

  //tutorial pages action types
  TUTORIAL_PAGES_LOADING: "TUTORIAL_PAGES_LOADING",
  TUTORIAL_PAGES_SUCCESS: "TUTORIAL_PAGES_SUCCESS",
  TUTORIAL_PAGES_FAIL: "TUTORIAL_PAGES_FAIL",

  //add policies action types
  ADD_POLICIES_LOADING: "ADD_POLICIES_LOADING",
  ADD_POLICIES_SUCCESS: "ADD_POLICIES_SUCCESS",
  ADD_POLICIES_FAIL: "ADD_POLICIES_FAIL",

  //legal action types
  LEGAL_LOADING: "LEGAL_LOADING",
  LEGAL_SUCCESS: "LEGAL_SUCCESS",
  LEGAL_FAIL: "LEGAL_FAIL",

  //legal action types
  FAQ_LOADING: "FAQ_LOADING",
  FAQ_SUCCESS: "FAQ_SUCCESS",
  FAQ_FAIL: "FAQ_FAIL",

  //contact us action types
  CONTACT_US_LOADING: "CONTACT_US_LOADING",
  CONTACT_US_SUCCESS: "CONTACT_US_SUCCESS",
  CONTACT_US_FAIL: "CONTACT_US_FAIL",

  //home action types
  HOME_LOADING: "HOME_LOADING",
  HOME_SUCCESS: "HOME_SUCCESS",
  HOME_FAIL: "HOME_FAIL",

  //deactivate account action types
  DEACTIVATE_ACCOUNT_LOADING: "DEACTIVATE_ACCOUNT_LOADING",
  DEACTIVATE_ACCOUNT_SUCCESS: "DEACTIVATE_ACCOUNT_SUCCESS",
  DEACTIVATE_ACCOUNT_FAIL: "DEACTIVATE_ACCOUNT_FAIL",

  //reactivate account action types
  REACTIVATE_ACCOUNT_LOADING: "REACTIVATE_ACCOUNT_LOADING",
  REACTIVATE_ACCOUNT_SUCCESS: "REACTIVATE_ACCOUNT_SUCCESS",
  REACTIVATE_ACCOUNT_FAIL: "REACTIVATE_ACCOUNT_FAIL",

  //news updates action types
  NEWS_UPDATES_LOADING: "NEWS_UPDATES_LOADING",
  NEWS_UPDATES_SUCCESS: "NEWS_UPDATES_SUCCESS",
  NEWS_UPDATES_FAIL: "NEWS_UPDATES_FAIL",

  //news read action types
  NEWS_READ_LOADING: "NEWS_READ_LOADING",
  NEWS_READ_SUCCESS: "NEWS_READ_SUCCESS",
  NEWS_READ_FAIL: "NEWS_READ_FAIL",

  //news delete action types
  NEWS_DELETE_LOADING: "NEWS_DELETE_LOADING",
  NEWS_DELETE_SUCCESS: "NEWS_DELETE_SUCCESS",
  NEWS_DELETE_FAIL: "NEWS_DELETE_FAIL",

  //confirm document action types
  CONFIRM_DOCUMENT_LOADING: "CONFIRM_DOCUMENT_LOADING",
  CONFIRM_DOCUMENT_SUCCESS: "CONFIRM_DOCUMENT_SUCCESS",
  CONFIRM_DOCUMENT_FAIL: "CONFIRM_DOCUMENT_FAIL",

  NOTIFICATIONS: "NOTIFICATIONS",
};
